# Generated by Django 4.2.2 on 2023-06-15 18:22

import django.core.validators
from django.db import migrations, models
import myPlantProject.my_plant_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_type', models.CharField(choices=[('OUTDOOR', 'Outdoor Plants'), ('INDOOR', 'Indoor Plants')], max_length=14)),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), myPlantProject.my_plant_app.models.validate_plant_name])),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2)])),
                ('first_name', models.CharField(max_length=20, validators=[myPlantProject.my_plant_app.models.validate_profile_name])),
                ('last_name', models.CharField(max_length=20, validators=[myPlantProject.my_plant_app.models.validate_profile_name])),
                ('profile_picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
